name: DevSecOps From Scratch

on:
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Verify source code
        run: |
          echo "Current directory:"
          pwd

          echo "Repository files:"
          ls -la

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit SAST Scan
        run: |
          bandit -r . -f txt

      - name: Hello DevSecOps
        run: echo "Starting my DevSecOps pipeline"