name: DevSecOps From Scratch

on:
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Verify source code
        run: |
          echo "Current directory:"
          pwd

          echo "Repository files:"
          ls -la

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit SAST Scan
        run: |
          bandit -r . -f json -o bandit-report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-sast-report
          path: bandit-report.json

      - name: Install pip-audit
        run: |
          pip install pip-audit

      - name: Run SCA Dependency Scan
        run: |
          pip-audit -r requirements.txt -f json -o pip-audit-report.json || true

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-sca-report
          path: pip-audit-report.json

      - name: Run Gitleaks Secret Scan
        continue-on-error: true
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build PyGoat Docker Image
        run: |
          docker build -t pygoat:devsecops .

      - name: Verify Docker Image
        run: |
          docker images

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pygoat:devsecops'
          format: 'json'
          output: 'trivy-report.json'
          severity: 'HIGH,CRITICAL'
          exit-code: '0'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-container-report
          path: trivy-report.json

      - name: Start PyGoat Container
        run: |
          docker run -d --name pygoat-ci -p 8000:8000 pygoat:devsecops

      - name: Verify PyGoat Container
        run: |
          docker ps